### ISSUE TITLE
Report file sizes

### ISSUE THREAD

**Issue by dl8bh** [fkie-cad/pcapFS#10]
It would be a great improvement to be able to see file-sizes in the filesystem.
If sorted by filter criteria, this could be used to break down network traffic by proportion.

Right now, I am copying data to a normal FS to get a great overview of proportion of targets (ports, protocols...) using normal linux utils like ncdu.

**Comment by jhilgert** [comment]
So nautilus shows me file sizes for all files and also directories, but somehow ncdu does not. I will have a look into that.

**Comment by dl8bh** [comment]
ls -s reports 0 for all file sizes - could it be, that nautilus calculates the sizes itself when the fs is not reporting values for the sizes?

**Comment by jhilgert** [comment]
The problem is that ncdu displays the file size by using the st_blocks attribute, indicating how many blocks are occupied by a file. This is also what ls -s returns, the size of a file in blocks. 
We were only filling the st_size attribute, since we are not exactly dealing with blocks in the virtual file system. Could you check out 6641a2a6647bef8025ebc33b17f36248af02da0d and see if this solves the problem for you?

**Comment by dl8bh** [comment]
Hi, I can confirm, that this PR solves the problem for me. Thank you for taking care of this!
