### ISSUE TITLE
install-ubuntu-dependencies.sh is missing install-catch2.sh entry

### ISSUE THREAD

**Issue by fxb-cocacoding** [fkie-cad/pcapFS#17]
It seems that the script `install-catch2.sh` is missing in the distribution-specific scripts for CentOS and Ubuntu.

**Comment by 0x4d4c** [comment]
This is more or less intentional. The reasoning behind this is that Catch2 is only required when you want to run the tests. It is not required to use pcapFS. We added a section on how to build pcapFS with testing capabilities in the README. Is this sufficient or do you think we should always install Catch2?

**Comment by fxb-cocacoding** [comment]
Okay, I will check this section out. I don't think it is necessary to compile Catch2 in general if it is only needed for testing.
