### ISSUE TITLE
Key file format

### ISSUE THREAD

**Issue by 0x4d4c** [fkie-cad/pcapFS#7]
We need a format for key files which is at least to some extent consistent for all protocols. This is needed to simplify the parsing and to support things like key IDs.

Maybe something like:
`PCAPFS_XOR_KEY keyID1 a b c ...`
where `a`, `b`, and `c` and so on are specific components/information of the corresponding protocol.

**Comment by axmahr** [comment]
You are right, the needed formats for key files are not the same for all protocols. However, how they have to be formatted at the moment enables an easier way to use them. For instance, SSL key files need to look like key log files generated when the environment variable `SSLKEYLOGFILE` is used, and using private RSA keys, the passed key file just has to be the private key itself in PEM format. The identification of the right connection to be decrypted is ensured by the inner logic of pcapFS or by the passed config file in case of XOR.
So, we probably won't introduce a consistent format for all key file types, since pcapFS is easier to use like that.
